; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:prod-M16]
platform = espressif32
board = m5stack-core-esp32-16M
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
lib_deps =
    m5stack/M5Stack@^0.4.6
build_flags =
    '-D NO_BOARD_FLAG=0'

[env:prod]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
lib_deps =
    m5stack/M5Stack@^0.4.6
build_flags =
    '-D NO_BOARD_FLAG=0'

[env:testing-M16]
platform = espressif32
board = m5stack-core-esp32-16M
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
lib_deps =
    m5stack/M5Stack@^0.4.6
build_flags =
    '-D NO_BOARD_FLAG=1'

[env:testing]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
lib_deps =
    m5stack/M5Stack@^0.4.6
build_flags =
    '-D NO_BOARD_FLAG=1'